### ISSUE TITLE
Question: how to set up PVs?

### ISSUE THREAD

**Issue by riuvshin** [Mirantis/kubeadm-dind-cluster#77]
hi guys!  thanks for the awesome project!

My PVC is always in "pending" state, probably because there is NO any PV by default

so my question is how to enable PVs and recycler ?

Thanks a lot!

**Comment by riuvshin** [comment]
Sorry for the dumb question,  I just thought that by default it will be similar to minikube, I deployed hostPath provisioner manually and now it works as I've expected.

**Comment by balboah** [comment]
@riuvshin how exactly? it would be awesome if someone could put in a note in the readme or somewhere

**Comment by riuvshin** [comment]
@balboah I've used very basic `hostpath-provisioner`

`pod.yaml`
```yaml
kind: Pod
apiVersion: v1
metadata:
  name: hostpath-provisioner
spec:
  containers:
    - name: hostpath-provisioner
      image: mazdermind/hostpath-provisioner:latest
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: pv-volume
          mountPath: /tmp/hostpath-provisioner
  volumes:
    - name: pv-volume
      hostPath:
        path: /tmp/hostpath-provisioner
```
`pvc.yaml`
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hostpath
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-hostpath"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
```
`sc.yaml`
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: example-hostpath
provisioner: example.com/hostpath
```
